from random import *
import string
from colorama import init, Fore, Back
init()

from user import User
from credentials import Credential

# User stories


def create_user(username, password):
    new_user = User(username, password)
    return new_user


def save_user(user):
    user.add_user()


# Credential stories

def create_credential(user, password, email, account):
    new_credential = Credential(user, password, email, account)
    return new_credential


def save_credential(credential):
    Credential.save_credential(credential)


def find_credential(account_name):
    return Credential.find_by_account(account_name)


def modify_credential_password(account_name, new_password):
    searched = find_credential(account_name)
    Credential.modify_account_password(searched, new_password)


def delete_credential(credential):
    credential.delete_credential()


def generate_password(password_length):
    characters = string.ascii_letters + string.punctuation + string.digits
    password = "".join(choice(characters) for x in range(0, password_length))
    return password


def display_credentials():
    return Credential.display_credentials()


# interface code

def main():
    print(Fore.CYAN + "Hello, welcome to your password manager.")
    print(Fore.LIGHTBLUE_EX + '-'*10)
    print('\n')
    print(Fore.GREEN + "We require you to login or create a user account")

    while True:
        print(Fore.LIGHTRED_EX + "Use this codes for user management: cu - Create a user, ll - Login to existing user, cl - Close app")
        appcode = input().lower()

        if appcode == 'cu':
            print(Fore.YELLOW + "New User")
            print('='*5)
            print("Enter Username")
            username = input()
            print('\n')
            print("Enter password")
            password = input()

            save_user(create_user(username, password))
            print('\n')
            print(Fore.MAGENTA + "User created now use code 'll' to login with the account details created")
            print('-'*10)
            print('\n')
        elif appcode == 'll':
            print(Fore.LIGHTMAGENTA_EX + "Username...")
            login_name = input()
            print("Password")
            login_key = input()
            login_response = User.user_login(login_name, login_key)

            while login_response:
                print(Fore.BLUE + "Use the following codes for credential management: cc - Create credential, ac - Show all credentials, dc - Delete credential, mc - modify credential, fc - Find Credential, ex - Exit")
                shortcode = input().lower()
                if shortcode == 'cc':
                    print("Username...")
                    credential_user_name = input()
                    print("Email...")
                    credetial_email = input()
                    print("Account...")
                    credential_account = input()
                    credential_password = ''
                    print(Fore.RED + "Password options: gp - To have password generated by credential manager, ep - To enter password manually")
                    password_option = input().lower()
                    if password_option == 'gp':
                        print("Enter desired length of password in number form")
                        desired_password_length = int(input())
                        credential_password = generate_password(desired_password_length)
                    elif password_option == 'ep':
                        credential_password = input()
                    else:
                        print(Fore.WHITE + "Use a valid code")

                    save_credential(create_credential(credential_user_name, credential_password, credetial_email, credential_account))

                elif shortcode == 'ac':
                    if display_credentials():
                        print(Fore.GREEN + "Here are all your credentials")
                        print('-'*10)
                        for credential in display_credentials():
                            print(Back.LIGHTCYAN_EX + f"Username -> {credential.user_name}, Email -> {credential.email_address}, Account -> {credential.account}, Password -> {credential.password}")

                        print(Back.RESET + Fore.RESET + '\n')
                    else:
                        print("You don't have any credentials")

                elif shortcode == 'fc':
                    print(Fore.LIGHTYELLOW_EX + "Enter account you desire")
                    search_find_acc = input()
                    if find_credential(search_find_acc):
                        found = find_credential(search_find_acc)
                        print(f"User - {found.user_name}, password - {found.password}, account - {found.account}")
                    else:
                        print("credential doesn't exist")
                    
                    print(Fore.RESET + '\n')

                elif shortcode == 'mc':
                    print(Fore.MAGENTA + "Search the account you want to change password")
                    serach_modifiy_acc = input()
                    changed_password = ''
                    if find_credential(serach_modifiy_acc):
                        print("Password options: gp - To have password generated by credential manager, ep - To enter password manually")
                        password_option = input().lower()
                        if password_option == 'gp':
                            print("Enter desired length of password in number form")
                            desired_password_length = int(input())
                            changed_password = generate_password(desired_password_length)
                        elif password_option == 'ep':
                            print("Enter your new password")
                            changed_password = input()
                        else:
                            print("Use a valid code")
                        modify_credential_password(serach_modifiy_acc, changed_password)

                    print(Fore.RESET + '\n')

                elif shortcode == 'dc':
                    print(Back.LIGHTRED_EX + Fore.WHITE + "Enter name of desired account")
                    search_del_acc = input()
                    if find_credential(search_del_acc):
                        delete_credential(find_credential(search_del_acc))
                        print("Account deleted")
                    else:
                        print("Account not found")

                    print(Back.RESET + '\n')
                elif shortcode == 'ex':
                    print(Back.LIGHTBLACK_EX + Fore.RED + "Bye .......")
                    print(Back.RESET + '\n')
                    break

                else:
                    print(Fore.WHITE + "Sorry Kindly use the following commands: cc - Create credential, ac - Show all credentials, dc - Delete credential, mc - modify credential, fc - Find Credential, ex - Exit")

        elif appcode == 'cl':
            print("It was nice having you around and welcome back...  :)")
            break

        else:
            print(Fore.WHITE + "Sorry I didn't get that please use the above stated codes.")


if __name__ == '__main__':

    main()
